name: Build and Deploy
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}


# 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
